Repository leanprover-community/mathlib4, pull requests merged in 2022-12, with the labels that each got.

#838 chore: bump to nightly-2022-12-03
  Mathlib/Data/Prod/Basic.lean
  Mathlib/Order/Basic.lean
  lake-manifest.json
  lean-toolchain
  test/Simps.lean
Labels: ready-to-merge

#836 feat: port Combinatorics.Quiver.ConnectedComponent
  Mathlib.lean
  Mathlib/Combinatorics/Quiver/ConnectedComponent.lean
Labels: mathlib-port, ready-to-merge

#820 feat: port CategoryTheory.NatIso
  Mathlib.lean
  Mathlib/CategoryTheory/Iso.lean
  Mathlib/CategoryTheory/NatIso.lean
  Mathlib/Tactic/Reassoc.lean
Labels: mathlib-port, ready-to-merge

#840 feat: Match mathlib#16761
  Mathlib/Algebra/Order/Monoid/Lemmas.lean
Labels: delegated

#1075 feat: port Data.Nat.Bits
  Mathlib.lean
  Mathlib/Data/Nat/Bits.lean
  Mathlib/Init/Data/Nat/Bitwise.lean
Labels: awaiting-author
