Repository leanprover-community/mathlib4, pull requests merged in 2023-11, with the labels that each got.

#6203 fix: patch for std4#195 (more succ/pred lemmas for `Nat`)
  Mathlib/Algebra/BigOperators/Intervals.lean
  Mathlib/Algebra/CharP/Basic.lean
  Mathlib/Algebra/GeomSum.lean
  Mathlib/AlgebraicTopology/AlternatingFaceMapComplex.lean
  Mathlib/AlgebraicTopology/SimplexCategory.lean
  Mathlib/Analysis/Calculus/FDeriv/Measurable.lean
  Mathlib/Combinatorics/Additive/Behrend.lean
  Mathlib/Combinatorics/Hall/Finite.lean
  Mathlib/Combinatorics/SimpleGraph/Regularity/Bound.lean
  Mathlib/Data/Fin/Basic.lean
  Mathlib/Data/Finset/Powerset.lean
  Mathlib/Data/Finset/Sort.lean
  Mathlib/Data/List/Cycle.lean
  Mathlib/Data/Nat/Basic.lean
  Mathlib/Data/Nat/Digits.lean
  Mathlib/Data/Nat/Totient.lean
  Mathlib/Data/Polynomial/Derivative.lean
  Mathlib/Data/Polynomial/EraseLead.lean
  Mathlib/Data/Polynomial/Module.lean
  Mathlib/Init/Data/Nat/Lemmas.lean
  Mathlib/Init/Meta/WellFoundedTactics.lean
  Mathlib/NumberTheory/Multiplicity.lean
  Mathlib/Probability/Martingale/Upcrossing.lean
  Mathlib/Probability/StrongLaw.lean
  Mathlib/RingTheory/IntegralClosure.lean
  Mathlib/RingTheory/MvPolynomial/NewtonIdentities.lean
  Mathlib/RingTheory/Polynomial/Bernstein.lean
  Mathlib/RingTheory/Polynomial/IntegralNormalization.lean
  Mathlib/Testing/SlimCheck/Gen.lean
  Mathlib/Util/DischargerAsTactic.lean
  lake-manifest.json
  test/lift.lean
Labels: ready-to-merge, t-number-theory, t-algebra

#8077 fix: patch for std4#194 (more order lemmas for `Nat`)
  Mathlib/Combinatorics/Composition.lean
  Mathlib/Combinatorics/SimpleGraph/Clique.lean
  Mathlib/Combinatorics/SimpleGraph/Coloring.lean
  Mathlib/Data/Fin/Basic.lean
  Mathlib/Data/Nat/Prime.lean
  Mathlib/Data/Nat/Squarefree.lean
  Mathlib/Init/Data/Nat/Lemmas.lean
  Mathlib/NumberTheory/FLT/Four.lean
  lake-manifest.json
Labels: delegated

#8176 chore: cleanup zify imports in preparation of upstreaming
  Mathlib/Tactic/Zify.lean
  test/Zify.lean
Labels: ready-to-merge

#8035 feat: a solution to if-normalization
  Archive.lean
  Archive/Examples/IfNormalization/Result.lean
  Archive/Examples/IfNormalization/Statement.lean
  Archive/Examples/IfNormalization/WithoutAesop.lean
Labels: ready-to-merge

#8184 fix: allow `peel` to handle `∃ ε > 0 ... ↔` goals
  Mathlib/Tactic/Peel.lean
  test/peel.lean
Labels: ready-to-merge, easy, t-meta

#8088 feat(Data/Matrix/Basic): add missing lemmas about `natCast` and `intCast`
  Mathlib/Data/Matrix/Basic.lean
Labels: ready-to-merge, t-algebra

#7756 feat: Hölder's inequality for more than 2 functions
  Mathlib/Algebra/BigOperators/Basic.lean
  Mathlib/Analysis/SpecialFunctions/Pow/NNReal.lean
  Mathlib/Data/Finset/Option.lean
  Mathlib/MeasureTheory/Integral/MeanInequalities.lean
Labels: ready-to-merge

#8220 chore: bump dependencies
  lake-manifest.json
Labels: awaiting-review

#8124 feat: Urysohn lemma in regular locally compact spaces
  Mathlib/Topology/EMetricSpace/Basic.lean
  Mathlib/Topology/Metrizable/Urysohn.lean
  Mathlib/Topology/Separation.lean
  Mathlib/Topology/UrysohnsLemma.lean
Labels: delegated, t-topology

#8233 chore: rename List.rdrop to dropRight
  Mathlib.lean
  Mathlib/Data/List/DropRight.lean
  Mathlib/Data/List/Rdrop.lean
Labels: awaiting-review

#8207 feat: Add NoAtoms instances for product measures
  Mathlib/MeasureTheory/Constructions/Prod/Basic.lean
Labels: ready-to-merge, t-measure-probability

#8230 chore(MeasureTheory/MeasurableSpace/Basic): change reference to file in docs
  Mathlib/MeasureTheory/MeasurableSpace/Basic.lean
Labels: ready-to-merge, easy

#8080 feat: add `Integrable.piecewise`
  Mathlib/MeasureTheory/Function/LpSeminorm.lean
  Mathlib/MeasureTheory/Function/LpSpace.lean
  Mathlib/MeasureTheory/Function/StronglyMeasurable/Basic.lean
  Mathlib/MeasureTheory/Integral/IntegrableOn.lean
Labels: ready-to-merge, t-measure-probability

#7341 feat: define `updateFinset` which updates a finite number components of a vector
  Mathlib.lean
  Mathlib/Data/Finset/Basic.lean
  Mathlib/Data/Finset/Update.lean
  Mathlib/Data/Set/Prod.lean
  Mathlib/Logic/Function/Basic.lean
  Mathlib/Logic/Unique.lean
Labels: awaiting-review

#8057 feat: lemmas analogous to fderiv_within_of_isOpen
  Mathlib/Analysis/Calculus/ContDiffDef.lean
  Mathlib/Analysis/Calculus/FDeriv/Basic.lean
  Mathlib/Geometry/Manifold/MFDeriv.lean
Labels: ready-to-merge, t-differential-geometry, t-analysis

#8191 feat(CategoryTheory/Monoidal): add lemmas for whiskering operators
  Mathlib/Algebra/Category/ModuleCat/Monoidal/Basic.lean
  Mathlib/Algebra/Category/ModuleCat/Monoidal/Symmetric.lean
  Mathlib/CategoryTheory/Monoidal/Types/Basic.lean
  Mathlib/RepresentationTheory/Action.lean
Labels: ready-to-merge, t-category-theory

#8163 feat(Data/../ENNReal): add lemmas about `ENNReal.ofReal`
  Mathlib/Data/Real/ENNReal.lean
Labels: ready-to-merge, t-algebra, t-order
