Repository leanprover-community/mathlib4, pull requests merged in 2024-02, with the labels that each got.

#10154 chore: adaptations for nightly-2024-02-01
  Mathlib/Algebra/Category/GroupCat/Basic.lean
  Mathlib/Algebra/DirectSum/Basic.lean
  Mathlib/Algebra/Group/Equiv/TypeTags.lean
  Mathlib/Algebra/Lie/Subalgebra.lean
  Mathlib/Algebra/Lie/Submodule.lean
  Mathlib/Algebra/Lie/Weights/Linear.lean
  Mathlib/Algebra/Module/Injective.lean
  Mathlib/Algebra/Order/WithZero.lean
  Mathlib/Algebra/Ring/Pi.lean
  Mathlib/Analysis/NormedSpace/AffineIsometry.lean
  Mathlib/CategoryTheory/Monad/EquivMon.lean
  Mathlib/CategoryTheory/Preadditive/HomOrthogonal.lean
  Mathlib/Combinatorics/Composition.lean
  Mathlib/Data/MvPolynomial/Expand.lean
  Mathlib/Lean/Meta/Simp.lean
  Mathlib/LinearAlgebra/CliffordAlgebra/EvenEquiv.lean
  Mathlib/LinearAlgebra/Projectivization/Subspace.lean
  Mathlib/NumberTheory/LucasLehmer.lean
  Mathlib/RepresentationTheory/GroupCohomology/Hilbert90.lean
  Mathlib/RingTheory/DedekindDomain/Ideal.lean
  Mathlib/RingTheory/HahnSeries.lean
  Mathlib/RingTheory/Valuation/ValuationSubring.lean
  Mathlib/Tactic/Abel.lean
  Mathlib/Tactic/Attr/Register.lean
  Mathlib/Tactic/DeriveTraversable.lean
  Mathlib/Tactic/FieldSimp.lean
  Mathlib/Tactic/NormNum/Core.lean
  Mathlib/Tactic/PushNeg.lean
  Mathlib/Tactic/ReduceModChar.lean
  Mathlib/Tactic/Ring/RingNF.lean
  Mathlib/Tactic/SimpIntro.lean
  Mathlib/Tactic/Simps/Basic.lean
  test/matrix.lean
Labels: awaiting-review

#10328 chore: adaptation PR for leanprover/lean4#3258 (fixing cache isssue in split tactic)
  Mathlib/Tactic/SplitIfs.lean
  lakefile.lean
  lean-toolchain
Labels: delegated, easy, v4.7.0

#10481 feat: Positivity extension for `Finset.prod`
  Mathlib/Algebra/BigOperators/Order.lean
  Mathlib/Analysis/Analytic/Composition.lean
  Mathlib/Analysis/Analytic/Inverse.lean
  Mathlib/Analysis/NormedSpace/BoundedLinearMaps.lean
  Mathlib/Analysis/NormedSpace/Multilinear/Basic.lean
  Mathlib/Analysis/NormedSpace/Multilinear/Curry.lean
  Mathlib/Data/Nat/Choose/Multinomial.lean
  Mathlib/Data/Nat/Factorial/BigOperators.lean
  Mathlib/MeasureTheory/Integral/TorusIntegral.lean
Labels: blocked-by-other-PR, awaiting-review, t-meta, t-algebra, t-order

#10600 fix(Tactic/ProjectionNotation): remove upstreamed delaborator
  Mathlib/Tactic/ProjectionNotation.lean
  test/delabLinearIndependent.lean
Labels: awaiting-review

#10585 chore: adaptations for nightly-2024-02-15
  Mathlib/Data/Rat/Defs.lean
  Mathlib/Init/Control/Combinators.lean
  Mathlib/Init/Logic.lean
  Mathlib/Init/Propext.lean
  Mathlib/Init/Set.lean
  Mathlib/Lean/Expr/Basic.lean
  Mathlib/Lean/Meta.lean
  Mathlib/Tactic/HaveI.lean
  Mathlib/Tactic/NormNum/Basic.lean
  Mathlib/Tactic/Positivity/Basic.lean
  Mathlib/Tactic/Widget/Conv.lean
  Mathlib/Testing/SlimCheck/Functions.lean
  Mathlib/Util/Delaborators.lean
  lake-manifest.json
  lakefile.lean
  lean-toolchain
  scripts/noshake.json
  test/DeriveToExpr.lean
  test/Expr.lean
  test/Real.lean
  test/UnsetOption.lean
  test/finset_repr.lean
  test/runCmd.lean
  test/says.lean
  test/simp_intro.lean
Labels: awaiting-review

#10679 chore: post success messages about nightly-testing
  .github/workflows/nightly_detect_failure.yml
Labels: awaiting-review
