Repository leanprover-community/mathlib4, pull requests merged in 2024-12, with the labels that each got.

#19984 chore: adaptations for nightly-2024-12-15
  lake-manifest.json
  lean-toolchain
Labels: auto-merge-after-CI

#20261 PR for testing import change for locating an instance
  Mathlib/Probability/Martingale/OptionalSampling.lean
  Mathlib/Topology/Instances/Discrete.lean
Labels: WIP

#20343 feature/expand_lemmas <- Jyxu/expand lemmas
  Mathlib/Algebra/Polynomial/Expand.lean
Labels: new-contributor
