Repository leanprover-community/mathlib4, pull requests merged in 2024-05, with the labels that each got.

#12587 chore: adaptations for nightly-2024-05-01
  Archive/Wiedijk100Theorems/BallotProblem.lean
  Mathlib/Combinatorics/SimpleGraph/Trails.lean
  Mathlib/Data/Multiset/Basic.lean
  Mathlib/Tactic/DeriveTraversable.lean
  Mathlib/Tactic/FieldSimp.lean
  lake-manifest.json
  lakefile.lean
  lean-toolchain
Labels: delegated

#12595 chore: adaptations for nightly-2024-05-02
  Mathlib/Data/PNat/Basic.lean
  Mathlib/Data/Rat/Lemmas.lean
  Mathlib/Tactic/FieldSimp.lean
  lean-toolchain
Labels: delegated

#12831 fix: use the right version of leanchecker
  .github/workflows/lean4checker.yml
Labels: CI, maintainer-merge

#12782 chore: adaptations for nightly-2024-05-09
  Mathlib/Algebra/Group/MinimalAxioms.lean
  Mathlib/CategoryTheory/Comma/Basic.lean
  Mathlib/Lean/Elab/Term.lean
  Mathlib/NumberTheory/Cyclotomic/Discriminant.lean
  Mathlib/Tactic/Convert.lean
  Mathlib/Tactic/FBinop.lean
  Mathlib/Tactic/Find.lean
  Mathlib/Tactic/FunProp/Decl.lean
  Mathlib/Tactic/Have.lean
  Mathlib/Tactic/NormNum/Pow.lean
  Mathlib/Tactic/TermCongr.lean
  Mathlib/Tactic/Variable.lean
  lake-manifest.json
  lakefile.lean
  lean-toolchain
Labels: awaiting-review

#12888 chore: run lean4checker cron frequently while we're debugging
  .github/workflows/lean4checker.yml
Labels: CI

#12896 chore: lake build ProofWidgets required for lean4checker
  .github/workflows/lean4checker.yml
Labels: awaiting-review

#12902 chore: adaptations for nightly-2024-05-14
  Mathlib/Algebra/Module/LinearMap/Polynomial.lean
  Mathlib/Analysis/Analytic/CPolynomial.lean
  Mathlib/Analysis/Calculus/ContDiff/Bounds.lean
  Mathlib/Analysis/Calculus/ContDiff/Defs.lean
  Mathlib/Analysis/NormedSpace/HahnBanach/Extension.lean
  Mathlib/Analysis/NormedSpace/Multilinear/Basic.lean
  Mathlib/Analysis/NormedSpace/OperatorNorm/Bilinear.lean
  Mathlib/Analysis/NormedSpace/OperatorNorm/Mul.lean
  Mathlib/Analysis/NormedSpace/OperatorNorm/NormedSpace.lean
  Mathlib/CategoryTheory/Filtered/Small.lean
  Mathlib/Data/Fin/VecNotation.lean
  Mathlib/Data/Nat/Choose/Multinomial.lean
  Mathlib/Data/Nat/Factorization/Basic.lean
  Mathlib/Data/Nat/Factors.lean
  Mathlib/Data/Nat/Prime.lean
  Mathlib/Data/Nat/PrimeFin.lean
  Mathlib/Data/Nat/Squarefree.lean
  Mathlib/Data/Rat/Defs.lean
  Mathlib/Data/Sym/Basic.lean
  Mathlib/Data/ZMod/Basic.lean
  Mathlib/GroupTheory/CommutingProbability.lean
  Mathlib/LinearAlgebra/Dual.lean
  Mathlib/LinearAlgebra/Orientation.lean
  Mathlib/LinearAlgebra/Semisimple.lean
  Mathlib/NumberTheory/ArithmeticFunction.lean
  Mathlib/NumberTheory/LSeries/HurwitzZetaOdd.lean
  Mathlib/NumberTheory/LegendreSymbol/JacobiSymbol.lean
  Mathlib/NumberTheory/NumberField/Units/DirichletTheorem.lean
  Mathlib/RingTheory/TensorProduct/Basic.lean
  Mathlib/RingTheory/WittVector/FrobeniusFractionField.lean
  Mathlib/SetTheory/Ordinal/FixedPointApproximants.lean
  Mathlib/Tactic/NormNum/Prime.lean
  Mathlib/Tactic/ToAdditive.lean
  lake-manifest.json
  lean-toolchain
  test/DeriveToExpr.lean
  test/Use.lean
  test/Variable.lean
  test/eval_elab.lean
Labels: delegated, ready-to-merge

#13069 chore: adaptations for nightly-2024-05-20
  .github/workflows/bors.yml
  .github/workflows/build.yml
  .github/workflows/build.yml.in
  .github/workflows/build_fork.yml
  Mathlib/CategoryTheory/Category/PartialFun.lean
  Mathlib/MeasureTheory/Measure/Lebesgue/Integral.lean
  Mathlib/Tactic/Check.lean
  Mathlib/Tactic/Explode.lean
  Mathlib/Tactic/ExtractGoal.lean
  lean-toolchain
Labels: awaiting-review

#13141 chore: adaptations for nightly-2024-05-23
  Mathlib/Data/Nat/Bits.lean
  Mathlib/Data/Nat/Bitwise.lean
  Mathlib/Tactic/Says.lean
  Shake/Main.lean
  lake-manifest.json
  lean-toolchain
  test/CompileInductive.lean
Labels: delegated

#13304 chore: adaptations for nightly-2024-05-27
  Mathlib/Analysis/Fourier/FourierTransformDeriv.lean
  Mathlib/Data/Int/Cast/Lemmas.lean
  Mathlib/Tactic/Linter/HashCommandLinter.lean
  lake-manifest.json
  lean-toolchain
Labels: ready-to-merge, maintainer-merge
