Repository leanprover-community/mathlib4, pull requests merged in 2024-11, with the labels that each got.

#18354 chore(scripts/bench): use `LEAN`, not `--lean`
  scripts/bench/temci-config.run.yml
Labels: CI

#19018 Work on lemma 'Polynomial.flt_catalan_deriv'
  Mathlib/NumberTheory/FLT/MasonStothers.lean
  Mathlib/NumberTheory/FLT/Polynomial.lean
  Mathlib/RingTheory/Radical.lean
Labels: WIP

#19037 Sorry-free polynomial FLT
  Mathlib/NumberTheory/FLT/Polynomial.lean
Labels: WIP

#19165 chore(RingTheory/Flat): tensor with localization preserves injectivity even over semirings
  Mathlib/Algebra/Module/LocalizedModule/IsLocalization.lean
  Mathlib/RingTheory/Flat/Localization.lean
  Mathlib/RingTheory/Localization/BaseChange.lean
Labels: blocked-by-other-PR, t-algebra

#19528 Flat local demo
  Mathlib/Algebra/Module/LocalizedModule/Basic.lean
  Mathlib/RingTheory/Flat/Localization.lean
Labels: t-algebra, new-contributor, large-import
