Repository leanprover-community/mathlib4, pull requests merged in 2024-06, with the labels that each got.

#13488 chore: run `lake update` when updating nightly-testing
  .github/workflows/nightly_merge_master.yml
Labels: CI

#13523 chore: adaptations for nightly-2024-06-04
  Mathlib/Algebra/Order/Group/Abs.lean
  Mathlib/Data/Nat/Bits.lean
  lean-toolchain
  test/norm_num.lean
Labels: delegated

#13712 fix: adapt to rcases fix
  Mathlib/RingTheory/DedekindDomain/Ideal.lean
Labels: blocked-by-core-PR

#13855 chore: updates for new dsimpNF linter
  Mathlib/Algebra/Module/Submodule/Pointwise.lean
  Mathlib/Algebra/PUnitInstances.lean
  Mathlib/Algebra/Ring/Equiv.lean
  Mathlib/Algebra/Star/StarAlgHom.lean
  Mathlib/CategoryTheory/Endomorphism.lean
  Mathlib/CategoryTheory/Groupoid/VertexGroup.lean
  Mathlib/CategoryTheory/Idempotents/Karoubi.lean
  Mathlib/RingTheory/Ideal/Operations.lean
  Mathlib/Topology/FiberBundle/Trivialization.lean
  lake-manifest.json
Labels: awaiting-review

#13283 feat(NumberTheory/PrimeCounting): Lemma: The `n`th prime is greater or equal `n + 2`.
  Mathlib/NumberTheory/PrimeCounting.lean
  Mathlib/Order/Monotone/Basic.lean
Labels: ready-to-merge, easy, t-number-theory, maintainer-merge

#13919 chore: adaptations for nightly-2024-06-17
  Archive/Imo/Imo1960Q1.lean
  Mathlib.lean
  Mathlib/Combinatorics/SimpleGraph/Coloring.lean
  Mathlib/Data/BinaryHeap.lean
  Mathlib/Data/Finset/Image.lean
  Mathlib/Data/List/Basic.lean
  Mathlib/Data/List/Enum.lean
  Mathlib/Data/List/Infix.lean
  Mathlib/Data/List/Perm.lean
  Mathlib/Data/List/Permutation.lean
  Mathlib/Data/List/Sublists.lean
  Mathlib/Data/Multiset/Basic.lean
  Mathlib/Data/Nat/Defs.lean
  Mathlib/Data/Nat/Factorization/Basic.lean
  Mathlib/GroupTheory/Coxeter/Inversion.lean
  Mathlib/Init/Data/Nat/Basic.lean
  Mathlib/ModelTheory/Encoding.lean
  Mathlib/NumberTheory/Padics/PadicVal.lean
  Mathlib/Testing/SlimCheck/Functions.lean
  lake-manifest.json
  lean-toolchain
  scripts/nolints.json
  scripts/style-exceptions.txt
  test/LibrarySearch/basic.lean
Labels: ready-to-merge

#14042 chore: adaptations for nightly-2024-06-22
  Mathlib/Algebra/BigOperators/Group/Finset.lean
  Mathlib/Algebra/BigOperators/Ring/Multiset.lean
  Mathlib/Algebra/Category/ModuleCat/Basic.lean
  Mathlib/Algebra/TrivSqZeroExt.lean
  Mathlib/AlgebraicGeometry/Morphisms/RingHomProperties.lean
  Mathlib/Analysis/Calculus/UniformLimitsDeriv.lean
  Mathlib/Combinatorics/Additive/FreimanHom.lean
  Mathlib/Combinatorics/SimpleGraph/Turan.lean
  Mathlib/Computability/PartrecCode.lean
  Mathlib/Control/Basic.lean
  Mathlib/Data/DFinsupp/Basic.lean
  Mathlib/Data/Fin/Tuple/NatAntidiagonal.lean
  Mathlib/Data/List/Basic.lean
  Mathlib/Data/List/Cycle.lean
  Mathlib/Data/List/Infix.lean
  Mathlib/Data/List/Intervals.lean
  Mathlib/Data/List/NatAntidiagonal.lean
  Mathlib/Data/List/Nodup.lean
  Mathlib/Data/List/Perm.lean
  Mathlib/Data/List/Permutation.lean
  Mathlib/Data/List/Range.lean
  Mathlib/Data/List/Sublists.lean
  Mathlib/Data/Matrix/PEquiv.lean
  Mathlib/Data/Multiset/Basic.lean
  Mathlib/Data/Multiset/Powerset.lean
  Mathlib/Data/Nat/Defs.lean
  Mathlib/Data/Prod/Basic.lean
  Mathlib/GroupTheory/Coxeter/Inversion.lean
  Mathlib/GroupTheory/Perm/Cycle/PossibleTypes.lean
  Mathlib/Init/Data/List/Instances.lean
  Mathlib/LinearAlgebra/TensorProduct/Graded/Internal.lean
  Mathlib/NumberTheory/SmoothNumbers.lean
  Mathlib/Tactic/ExtendDoc.lean
  Mathlib/Tactic/HelpCmd.lean
  Mathlib/Topology/Homotopy/HomotopyGroup.lean
  Mathlib/Topology/MetricSpace/Isometry.lean
  Mathlib/Topology/MetricSpace/PseudoMetric.lean
  Mathlib/Topology/UniformSpace/UniformConvergence.lean
  Mathlib/Topology/UniformSpace/UniformConvergenceTopology.lean
  Mathlib/Topology/UniformSpace/UniformEmbedding.lean
  lake-manifest.json
  lean-toolchain
Labels: delegated

#14148 chore: adaptations for nightly-2024-06-25
  Archive/Examples/IfNormalization/Result.lean
  Mathlib/AlgebraicGeometry/Morphisms/RingHomProperties.lean
  Mathlib/CategoryTheory/EffectiveEpi/Preserves.lean
  lake-manifest.json
  lean-toolchain
  test/CategoryTheory/Elementwise.lean
  test/congr.lean
  test/convert.lean
Labels: awaiting-review
