Repository leanprover-community/mathlib4, pull requests merged in 2025-05, with the labels that each got.

#24524 chore: adaptations for nightly-2025-05-01
  Mathlib/Algebra/Exact.lean
  lake-manifest.json
  lakefile.lean
  lean-toolchain
Labels: delegated

#24589 feat(Algebra/Category): some lemmas about adjunctions in `Under R`
  Mathlib.lean
  Mathlib/Algebra/Category/Ring/Topology.lean
  Mathlib/Algebra/Category/Ring/Under/Adjunctions.lean
  Mathlib/Algebra/Category/Ring/Under/Basic.lean
Labels: t-category-theory, t-algebra, new-contributor

#24569 chore: adaptations for nightly-2025-05-03
  lean-toolchain
Labels: dependency-bump

#25013 ci: simplify style lint build job and move towards end of workflow
  .github/build.in.yml
  .github/workflows/bors.yml
  .github/workflows/build.yml
  .github/workflows/build_fork.yml
Labels: CI
