Repository leanprover-community/mathlib4, pull requests merged in 2025-01, with the labels that each got.

#20443 jmc lie theorem diff
  Mathlib/Algebra/Lie/LieTheorem.lean
  Mathlib/Algebra/Lie/Submodule.lean
  Mathlib/Algebra/Lie/Weights/Basic.lean
  Mathlib/LinearAlgebra/Trace.lean
Labels: t-algebra

#20470 feat(1000): fill in more entries
  Mathlib/Analysis/InnerProductSpace/Projection.lean
  Mathlib/Combinatorics/SetFamily/LYM.lean
  Mathlib/MeasureTheory/Covering/Besicovitch.lean
  Mathlib/MeasureTheory/Covering/Vitali.lean
  docs/1000.yaml
Labels: documentation

#20804 chore: adaptations for nightly-2025-01-16
  Mathlib/Computability/Tape.lean
  Mathlib/Data/List/Basic.lean
  Mathlib/Data/List/Forall2.lean
  Mathlib/Data/List/Monad.lean
  Mathlib/Data/List/Permutation.lean
  lake-manifest.json
  lean-toolchain
Labels: large-import

#20763 feat: `casesm` tactic reuses hypothesis name if only one new hypothesis
  Mathlib/Tactic/CasesM.lean
  MathlibTest/casesm.lean
Labels: delegated, t-meta

#20997 Mc products refactor
  Mathlib/Algebra/Algebra/Pi.lean
  Mathlib/Algebra/Group/Invertible/Basic.lean
  Mathlib/RingTheory/Localization/Basic.lean
  Mathlib/RingTheory/Localization/Pi.lean
Labels: new-contributor

#21245 chore: adaptations for nightly-2025-01-29
  Mathlib/Algebra/LinearRecurrence.lean
  Mathlib/Algebra/TrivSqZeroExt.lean
  Mathlib/Analysis/Analytic/Composition.lean
  Mathlib/Combinatorics/Enumerative/Composition.lean
  Mathlib/Data/List/Basic.lean
  Mathlib/Data/List/Enum.lean
  Mathlib/Data/List/Indexes.lean
  Mathlib/Data/List/OfFn.lean
  Mathlib/Data/List/ProdSigma.lean
  Mathlib/Data/List/Sigma.lean
  Mathlib/Data/List/Sublists.lean
  Mathlib/Data/List/ToFinsupp.lean
  Mathlib/Data/Nat/Digits.lean
  Mathlib/Data/Sigma/Basic.lean
  Mathlib/Data/ULift.lean
  Mathlib/NumberTheory/Ostrowski.lean
  Mathlib/Order/RelSeries.lean
  Mathlib/Tactic/DeriveTraversable.lean
  Mathlib/Tactic/Linarith/Oracle/FourierMotzkin.lean
  Mathlib/Tactic/Linarith/Oracle/SimplexAlgorithm.lean
  Mathlib/Tactic/Linarith/Oracle/SimplexAlgorithm/Datatypes.lean
  Mathlib/Tactic/Linarith/Verification.lean
  Mathlib/Tactic/Linter/TextBased.lean
  Mathlib/Tactic/MkIffOfInductiveProp.lean
  Mathlib/Tactic/Widget/StringDiagram.lean
  lake-manifest.json
  lakefile.lean
  lean-toolchain
Labels: large-import
